services:
  - type: web
    name: rituals-backend-3
    env: docker
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://ep-long-feather-a1sre95p-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
      - key: SPRING_DATASOURCE_USERNAME
        value: neondb_owner
      - key: SPRING_DATASOURCE_PASSWORD
        value: npg_wBhCSRMz42sn
      - key: MAIL_USERNAME
        value: shivanimanivannan2@gmail.com
      - key: MAIL_PASSWORD
        value: lvvleawwmnegxrjx
