databases:
  - name: rituals-db
    plan: free

services:
  - type: web
    name: rituals-backend
    env: docker
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: rituals-db
          property: connectionStringJDBC
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: rituals-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: rituals-db
          property: password
